version: '3.7'

volumes:
  db_data:

services:
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: foxgres
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    command: ["cargo", "run"]
    depends_on:
      - db
