name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: rust-foxgres
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    env:
      LOG_LEVEL: debug
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: foxgresrust
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin

    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: foxgresrust
        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Wait for PostgreSQL
        run: sleep 15

      - name: Run database migrations
        env:
          PGPASSWORD: ${{ env.DATABASE_PASSWORD }}
        run: |
          psql -h localhost -p 5432 -U admin -d foxgresrust -f migrate/create_db.sql
          psql -h localhost -p 5432 -U admin -d foxgresrust -f migrate/insert_db.sql

      - run: cargo build --verbose
      - run: cargo test --verbose
